### ISSUE TITLE
getting started guide - last version

### ISSUE THREAD

**Issue by brownman** [sinisterchipmunk/jax#17]
TESTING
i always dreamed about a webgl framework which is completly testable..
and encourage testing.
GUIDE
thanks to similarity to the famous rails guide    - 
it is much more CHEERFUL to start JAXING !
VIDEO
expose some awesomeness of the Jax:
consider  posting  video example to youtube/vimeo
## NEXT FEATURES:
1.  INHERITANCE
   encourage NEW developers to extend jax as a FLEXIBLE framework:
   can u show a way for developers to extend jax by making a project  which targets  extending some jax feature ?
2. RAILS VIEW MODEL
   please show how to adopt  jax as the main rails view model.
   and maybe show a sample of a well tested jaxy and ajaxy application. 
3. WALK THROUGH: (text guide/video clip)
   how to cook: a testable game  ?
   let me ask for a guide which examples a development of a game in TDD manner .
4. FUN DEMOS 
   visualize some data structure: -a javascript/ruby   memory stack/heap | -a git repo | -class hirarchy (maybe code that expose itself?)
   robots battle game - ran robot codes - evaluate javascript code at runtime..
   collaborative editor but one that focuses on only 1 game - it will  let u play+extend the game source code.

**Comment by sinisterchipmunk** [comment]
1. This is in the works. I'm _tentatively_ (that is, I make no guarantees) targeting v1.1.0 for a new plug-in system that will allow developers to not only extend Jax itself, but to collectively share code such as shaders, meshes, etc. This will, of course, have a comprehensive guide associated with it.
2. As mentioned in the past, Jax is not going to cater specifically to Rails. It is what it is: a completely separate framework that happens to share a lot of similarities with rails. With that said, I'm a total Rails fanboy and it's only natural that the next step is to create a new "jax-rails" gem to adapt Jax to Rails projects. Keep your eyes open, but don't look for it from Jax proper.
3. I hope to do something similar to this with the testing guide, when I have time to write it. There's a lot of work to be done, yet.
4. These are a bit beyond the scope of what Jax is. Better idea: use Jax to implement these, then let me know so I can link to the projects!
