### ISSUE TITLE
needed: simple example

### ISSUE THREAD

**Issue by brownman** [sinisterchipmunk/jax#2]
how to run the server ?
where to find index.html ?

**Comment by sinisterchipmunk** [comment]
I'll be adding more detailed instructions via the readme, wiki and probably a separate dedicated website at some point in the future. For now, look at the example app in spec/example_app/.

The example app server can be run with:

```
bundle exec rake jasmine
```

and runs on port 8889 (it currently says 8888 but this is incorrect).

You can customize the HTML file in spec/example_app/spec/javascripts/support/run.html.erb but you shouldn't have to do this. Instead modify the javascript source files directly at spec/example_app/app/*_/_.js.

More helpful instructions will be added in the near future.

**Comment by brownman** [comment]
## i get to c no picture/drawings 

courthouse_controller.js:9Uncaught TypeError: Cannot call method 'addLightSource' of undefined

**Comment by sinisterchipmunk** [comment]
Make sure you have the latest code (do a git pull) and do this frequently. I usually make several commits per day. It should be rendering something as of the latest commit, but also keep in mind that I reserve the right to commit broken code until the first release. After that I'll try to keep all tests running clean, but until v0.0.1 is released (hopefully within a few weeks, depending on my schedule) I make no guarantees.
