### ISSUE TITLE
guide has to be more responsive

### ISSUE THREAD

**Issue by brownman** [sinisterchipmunk/jax#22]
1.
guide.responsive?
if i want to report a line with my notes - i wish it to be easy as clicking that line.

2.
http://guides.jaxgl.com/getting_started.html
section: 8.4.2 The Dungeon Mesh
           /\* walls */
            if (x == 0            || row[x-1]    == 'X') drawSideWall(x, y, -1);   // left
            if (y == 0            || map[y-1][x] == 'X') drawFrontWall(x, y, 1);   // front
            if (x == row.length-1 || row[x+1]    == 'X') drawSideWall(x, y, 1);    // right
            if (y == map.length-1 || map[y+1][x] == 'X') drawFrontWall(x, y, -1);  // back

it doesn't make sense -
y would u want to draw 4 walls to represent the middle 'X' (which shouldn't be visible):
XXX
XXX
XXX

3.
may Dungeon to be transformed to a simple sokoban game ?
http://www.rubyquiz.com/quiz5.html
- with a feature of adding new levels

**Comment by sinisterchipmunk** [comment]
1. Why not just quote the section/subsection? Something like `section 3.2.1 is horribly written, it should say this: ". . ."`
2. You're misunderstanding the code. It doesn't check if the _current_ cell is 'X', it checks if the _adjacent_ cell is 'X' (e.g. a wall). In the code directly preceding your quote, the _current_ cell is skipped entirely if it is 'X', which prevents the condition you described in this issue.
3. It certainly could be, but that's beyond the scope of the guide and something you'd want to implement in your own app. I've never played Sokoban, personally.
