### ISSUE TITLE
deprecation warning: Gem.available? is deprecated

### ISSUE THREAD

**Issue by rubychan** [sinisterchipmunk/jax#23]
With RubyGems 1.8.5 I get:

```
NOTE: Gem.available? is deprecated, use Specification::find_by_name. It will be removed on or after 2011-11-01.
Gem.available? called from /Users/murphy/.rvm/gems/ruby-1.8.7-p334/gems/jasmine-1.0.2.1/lib/jasmine/base.rb:64.
```

**Comment by sinisterchipmunk** [comment]
As the error message implies, this is a problem with Jasmine, not Jax itself. The corresponding Jasmine issue has already been addressed at : https://github.com/pivotal/jasmine-gem/pull/41 so there should be a release addressing it shortly if there hasn't been already.

**Comment by rubychan** [comment]
Sorry, I confused Jasmine and Jax again -_-'
