### ISSUE TITLE
rake jasmine not working

### ISSUE THREAD

**Issue by nat-n** [sinisterchipmunk/jax#26]
I just started trying to follow the tutorial. Installing the jax gem v2.0.2, creating the dungeon project and the `bundle install` command all seemed to work fine.

However `rake jasmine` resulted in:
`rake aborted!
Don't know how to build task 'jasmine'`

This was not with previous versions of jax.

**Comment by sinisterchipmunk** [comment]
The `rake jasmine` task has been replaced with the `jax server` command. In a Rails application, this is equivalent to `rails server`.

**Comment by sinisterchipmunk** [comment]
The tutorials should have all been updated with the new command. If you see the old command anywhere, please raise that as a separate issue. Thanks!
