### ISSUE TITLE
GL_INVALID_ENUM error on Safari

### ISSUE THREAD

**Issue by hiteshjasani** [sinisterchipmunk/jax#31]
All of the demo apps fail with the following error message on Safari (Version 5.1.1 (7534.51.22)) on OSX Lion.

Error:  Error:  GL error in jax-canvas: 1280
(GL_INVALID_ENUM)

**Comment by sinisterchipmunk** [comment]
I am able to reproduce this error in Snow Leopard. It's proving tricky to debug, but wanted to let you know I'm working on it.

**Comment by hiteshjasani** [comment]
No worries.  It's not impacting me as I was just browsing your code and decided to try it out.

**Comment by sinisterchipmunk** [comment]
I'm about to push Jax v2.0.3, containing this fix.
