### ISSUE TITLE
Scaffold generates faulty tests

### ISSUE THREAD

**Issue by nat-n** [sinisterchipmunk/jax#38]
To replicate:

`jax new bugdemo
cd bugdemo
jax generate scaffold test_breaker
jax server`

Now in the test suite: `Error: Route not recognized: 'test_breaker/index' (controller not found)

I guess scaffolds/controllers shouldn't contain underscores, so maybe generate should complain?

**Comment by sinisterchipmunk** [comment]
Thanks for reporting this. It should have camelized the name (test_breaker => TestBreaker) automatically.
