### ISSUE TITLE
Would be handy if buildMouseEvent method were public

### ISSUE THREAD

**Issue by nat-n** [sinisterchipmunk/jax#61]
Referring to https://github.com/sinisterchipmunk/jax/blob/55f6d07f85e3dea55232dfbf768517f34c3850e1/lib/assets/javascripts/jax/events.js#L87

This would be useful as a public method for instance, when layering another non Jax cavas (such as  Raphael SVG canvas) above part of the Jax WebGL canvas, and wanting mouse move and click events to be easily re-routable so they fire in the active controller as if the higher canvas weren't there.

**Comment by sinisterchipmunk** [comment]
A lot of private APIs are going to be made public in the next release. I'll make sure this tops the list.

**Comment by sinisterchipmunk** [comment]
Event handling has been completely rewritten in v3.0, and this functionality has been moved from `Jax.Context` into `Jax.Input.Mouse`. See [mouse.js.coffee#L44](https://github.com/sinisterchipmunk/jax/blob/51354f68e5f9f6dae966be366be4a8ef3c27badf/lib/assets/javascripts/jax/input/mouse.js.coffee#L44).

The `trigger` method is used to create DOM events and dispatch them to the underlying `canvas` element, which will then dispatch the event to Jax and anything else listening to the canvas. The `processEvent` method works one level higher, bypassing the `canvas` element and dispatching events directly to Jax.
