### ISSUE TITLE
Some thumbnails in docs don't work

### ISSUE THREAD

**Issue by MichaelHoste** [sinisterchipmunk/jax#63]
With Chrome, I can only see two thumbnails ("Perlin Noise" and "Jax.Material.Custom") in your documentation (http://docs.jaxgl.com/) and I don't see any screenshot when the 3D render fails.

No errors in the javascript console... 

Configuration :
- Mac OS X 10.6.8
- Chrome 22
- 5yo Macbook 
- Core 2 duo
- 4Go ram
- Intel GMA X3100‎

Notes :
- each of the thumbnails work great on Firefox (slow when a lot of them) !
- On a new macbook air and Chrome 22 everything works fine !

**Comment by sinisterchipmunk** [comment]
Thanks for the report. Do you get any red text about being unable to load screenshots (it would be where the screenshots _should_ be), or just black boxes?

**Comment by MichaelHoste** [comment]
Not red text nor black boxes, juste empty white space.

Screenshot :

![Image](https://dl.dropbox.com/u/9553927/jaxgl.png)

**Comment by sinisterchipmunk** [comment]
No red text indicates that the system _thinks_ all is fine. This leads me to wonder if it isn't a driver bug or at least limitation. Currently I'm curious as to whether it's a problem with multiple contexts, but I can't confirm that suspicion at this time and, indeed, it could be one of a ton of other things as well. Will continue researching this.

In the meantime, just to verify:

Do all of the Jax v2.x demos ( http://sinisterchipmunk.github.com ) run for you?

Can you go back to the docs and just click through the drop-down menu at the top right, and list here exactly which demos are running for you and which ones are not?

Thanks!

**Comment by MichaelHoste** [comment]
The Jax v2.x demos don't run with Chrome on my computer... Javascript errors are raised :

Error: ERROR: 0:36: '**import_functions_depth_map**' : macro name is reserved 
Error: ERROR: 0:42: '**import_functions_lights**' : macro name is reserved 
Error: ERROR: 0:50: '**import_functions_noise**' : macro name is reserved 
Error: ERROR: 0:596: '**import_functions_perlin_height_map**' : macro name is reserved

The only two Jax v3 demos that work with Chrome on my computer are "Perlin Noise" and "Jax.Material.Custom" (I tried every drop-down demos). In most of the pages, my computer slows down for 10-15 seconds and then the page is drawn with no thumbnails at all. Don't forget I tried with the new macbook air of a friend with the same Chrome and everything worked fine !

Just for info, I'm able to see this kind of 3D view smoothly with Chrome so my browser seems totally able to render 3D content : https://sketchfab.com/show/fvSRYJw5TTj03ScEZtuzlH0wVBX

Again, in Firefox most of the Jax v2.x works (some of them seems to freeze my old computer though) and all the Jax v3 works perfectly (except inputs : https://github.com/sinisterchipmunk/jax/issues/64)

**Comment by sinisterchipmunk** [comment]
I discovered the reserved macro names issue in Jax v2.x while working on 3.0, and haven't had time to backport the resolution. Unfortunate that you're affected by this right now...

Right, I'd forgotten that you said it works on Firefox. That complicates things. It can't be purely due to having multiple contexts on the same page then. Even if it's exhausting video resources, it should be doing that in FF as well.

Ok, can you go back to the docs page (doesn't matter which one) and paste this code into the Chrome console: https://gist.github.com/3839250 -- it should produce a black canvas at the top-left of the page, with a red square in the middle.

**Comment by MichaelHoste** [comment]
It produces a black canvas at the top-left of the page.... but no red square in the middle :-/
And still no javascript errors

**Comment by sinisterchipmunk** [comment]
Progress, though it doesn't feel like it. :)

I'm going to again compare your GPU specs ( [developer.apple/opengl/capabilities](https://developer.apple.com/graphicsimaging/opengl/capabilities/GLInfo_1068.html) is a wonderful thing btw) to the default shaders produced by Jax. Maybe I missed something last time.

In the meantime, if you wouldn't mind running the [WebGL conformance tests](https://www.khronos.org/registry/webgl/conformance-suites/1.0.1/webgl-conformance-tests.html) in Chrome, it would help to have the peace of mind. Please list any failures here. Keep in mind that a failure or two isn't a smoking gun, as I get a few failures on my end as well, but it could uncover clues if there's some low-level issue at work here.

**Comment by MichaelHoste** [comment]
Actually, I have a lot of failures : https://gist.github.com/3840329

Tests PASSED: 3241
Tests FAILED: 657
Tests TIMED OUT: 31

(do you prefer the HTML Summary ?)

**Comment by sinisterchipmunk** [comment]
Thanks. I've forwarded this on to the WebGL mailing list to see if we should consider this a problem with the browser. They've asked me, to ask you, to clone [the conformance suite](https://github.com/KhronosGroup/WebGL) and run the tests again locally. This will ensure no network-related failures.

WebGL security restrictions will prevent you from just opening the files directly, so you need to start a server in the directory into which you cloned the project, with this command:

```
python -m SimpleHTTPServer
```

Then you can access the server at [http://localhost:8000](http://localhost:8000).

Please include the following for reference (even though you've already given some of it above):
- text summary of the tests
- Browser/Version
- Operating System/Version
- GPU Model
- Driver Version

**Comment by MichaelHoste** [comment]
I ran the test locally with the SimpleHTTPServer and the results seem exactly the same : 

Tests PASSED: 3241
Tests FAILED: 657
Tests TIMED OUT: 31

Text summary of the tests : https://gist.github.com/3848167
Browser : Chrome 22.0.1229.79
OS : MacOS 10.6.8
GPU Model : GMA X3100
Driver Version : I really don't know about it. I just keep my system up to date. (Maybe these lines are useful ? "Fournisseur : Intel (0x8086) / Identifiant du périphérique : 0x2a02 / Identifiant de révision : 0x0003")

If it's just an issue with my specific configuration, I'm not sure it's worth the time to correct it...
I'll buy a new computer soon anyway ;-)

**Comment by sinisterchipmunk** [comment]
> If it's just an issue with my specific configuration, I'm not sure it's worth the time to correct it...

Well, I'm concerned because other users may have a similar configuration. As a Web technology, we need to take all reasonable steps toward compatibility.

Looks like this issue is bound for the Chrome issue tracker. Before I send it that way though, can you run the conformance tests on Firefox and post the text summary? I'm hopeful that FF checks out since Jax isn't failing on it. It will be useful for the Chrome guys to cross reference against.

There are several other existing issues in the Chrome tracker dealing with the X3100, and I was given a warning that I'll repeat here for posterity:

> Note that one possible outcome of this may be that the X3100 (or its older 10.6 driver) will be blacklisted.

**Comment by MichaelHoste** [comment]
I made a breakthrough when testing with Firefox.

Firefox completely freezed on 5 different conformance tests so I unchecked these specific tests and I got a nice "8650 of 8735 passed". Those "freezing tests" are glsl-function-dot, glsl-function-faceforward, glsl-function-length, glsl-function-normalize and glsl-function-reflect.

For my peace of mind, I re-tested Chrome with the same unchecked tests and I now have a nice "8610 of 8753 passed" (Chrome didn't freeze but WebGL must have crashed for the next tests). So less success than Firefox. I think this is a good place to start.

Here are the text reports :

Firefox : https://gist.github.com/3851350
Chrome : https://gist.github.com/3851353

If I'm right, there are 2 issues :
- 5 freezing/crashing tests (related to my system)
- Some tests that failed in Chrome and not in Firefox (related to Chrome).

**Comment by sinisterchipmunk** [comment]
Sorry for the delay. I wanted to get together as much feedback from the mailing list as possible.

And the feedback I've gotten doesn't sound particularly encouraging. It sounds like the X3100 has had problems relating to OpenGL all along, owing mostly to a crappy driver implementation. Further, it appears that the X3100 isn't even supported on the latest OSX, so an OS upgrade is unlikely to help.

For your reference, here's a link to the archived thread in the mailing list, beginning with my original email:

https://www.khronos.org/webgl/public-mailing-list/archives/1210/msg00022.html

I'll note that according to your Firefox tests, it seems that there are issues that center around core functions like `dot`, `normalize`, and `reflect`. Unfortunately, these GLSL functions are pretty crucial to Jax shaders, and the only solution that I'm aware of (if it would even work) would be to re-implement those functions at a higher level in GLSL. I'm not certain how the compiler works these things out, but I suspect that doing so would remove hardware acceleration for the offending functions, thus significantly impacting performance across the board. The only way I can see making this work, without reducing performance on other machines that are working properly, would be to pick and choose which set of functions to call at runtime. Unfortunately I don't think we can get enough information about the GPU, driver, browser and OS to make an informed decision, and we can't very well go crashing peoples' browsers "just to find out". Not to mention the branching of code that'd have to be maintained: at some point we just have to draw a line.

If you would like, feel free to post this issue to the [Chrome](http://code.google.com/p/chromium/issues/list) and [Firefox](https://bugzilla.mozilla.org/) issue trackers, but I think this is as far as we can take the issue as it relates to Jax, so I'm going to close the issue.

**Comment by MichaelHoste** [comment]
You're right to draw the line somewhere. If my GPU is really crappy (and it seems it IS crappy), it's not your job to make it work. I hope it will affect only a few Jax users.

Thanks a lot for trying to solve this difficult and very specific issue !
