### ISSUE TITLE
Materials view of development suite crashes .rc1

### ISSUE THREAD

**Issue by nat-n** [sinisterchipmunk/jax#65]
New rails project with rails 3.2.8
`gem 'jax', '~> 3.0.0.rc1'`
$ bundle install
$ rake db:migrate
$ rails s
chrome => http://0.0.0.0:3000/jax/shader_editor

page seems to not fully load, console shows:

Uncaught TypeError: Object function Material(options, name) {
...
    } has no method 'all' :3000/assets/jax/shader_editor.js?body=1:43
(anonymous function) :3000/assets/jax/shader_editor.js?body=1:43
fire jquery.js:975
self.fireWith jquery.js:1083
jQuery.extend.ready jquery.js:407
DOMContentLoaded

test suite tab also seems to not load fully (no content), but doesn't report any errors.

**Comment by sinisterchipmunk** [comment]
`Jax.Material.all` was removed unintentionally, and that is why this fails.

I've been thinking of better ways to test, especially to catch issues like this one. I've some ideas but haven't had a chance to experiment.
