### ISSUE TITLE
generated materials don't parse 3.0.0.rc1

### ISSUE THREAD

**Issue by nat-n** [sinisterchipmunk/jax#66]
I tried generating a new material but then when I try to load the development suite it displays a Psych::SyntaxError
`(<unknown>): mapping values are not allowed in this context at line 18 column 9`.

pointing it seems to this part of the newly generated material resource file

`
17 |   shininess: 60
18 |    - type: PhongSpecular
19 |    - type: LambertDiffuse
`

**Comment by sinisterchipmunk** [comment]
Interesting. Looks like the "layers" element wasn't generated. Thanks for reporting this!

Until it's fixed you can manually add "layers:" like so:

```
17 | shininess: 60
18 | layers:
19 | - type: PhongSpecular
20 | - type: LambertDiffuse
```
