### ISSUE TITLE
can't get the demo to work

### ISSUE THREAD

**Issue by brownman** [sinisterchipmunk/jax#7]
cd /jax/spec/example_app/
bundle exec rake jasmine

running chrome on linux :
rise errors:
jax.js:2799Uncaught Error: Attribute location for attribute 'VERTEX_TEXCOORDS' could not be found!

**Comment by sinisterchipmunk** [comment]
Strange. I've been doing a lot of dev lately so could have broken something, but I've yet to see this on Mac, so it may be OS-specific.

It's going to be another week or so before I'm back on my linux box. In the meantime, can you retest with the latest commits?

**Comment by brownman** [comment]
1.
couldn't break webrick proccess with control+c, as i can in rails

^C[2011-04-20 05:23:43] ERROR Interrupt: 
    /home/dao01/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/webrick/server.rb:90:in `select'
^C[2011-04-20 05:23:43] ERROR Interrupt: 
    /home/dao01/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/webrick/server.rb:90:in`select'

2.

should be enabled
ReferenceError: Jax is not defined
Error: ReferenceError: Jax is not defined
    at new <anonymous> (http://0.0.0.0:8889/__JASMINE_ROOT__/lib/jasmine.js:94:50)
    at [object Object].fail (http://0.0.0.0:8889/__JASMINE_ROOT__/lib/jasmine.js:1963:27)
    at [object Object].execute (http://0.0.0.0:8889/__JASMINE_ROOT__/lib/jasmine.js:970:15)
    at [object Object].next_ (http://0.0.0.0:8889/__JASMINE_ROOT__/lib/jasmine.js:1739:31)
    at http://0.0.0.0:8889/__JASMINE_ROOT__/lib/jasmine.js:1729:18
TypeError: Cannot call method 'isEnabled' of undefined
Error: TypeError: Cannot call method 'isEnabled' of undefined
    at new <anonymous> (http://0.0.0.0:8889/__JASMINE_ROOT__/lib/jasmine.js:94:50)
    at [object Object].fail (http://0.0.0.0:8889/__JASMINE_ROOT__/lib/jasmine.js:1963:27)
    at [object Object].execute (http://0.0.0.0:8889/__JASMINE_ROOT__/lib/jasmine.js:970:15)
    at [object Object].next_ (http://0.0.0.0:8889/__JASMINE_ROOT__/lib/jasmine.js:1739:31)
    at http://0.0.0.0:8889/__JASMINE_ROOT__/lib/jasmine.js:1729:18

**Comment by brownman** [comment]
u may consider maintaining  separate branch for each O.S .. 
at least until the big green merge.

i used to like jax ! ;(

**Comment by sinisterchipmunk** [comment]
The ctrl+c issue is not mine, it is an issue with Jasmine. To my knowledge, the issue has been addressed and will be resolved with the next release of Jasmine. On *nix machines, you can use:

```
ps -ef |grep jasmine
kill -9 [process id]
```

but I'm not sure of any easier way to kill the server. This has been bugging me for a while now, too.

I will look into the other errors as soon as I can. I am away from my main computer on business for a few more days, so I am only using my Mac for development, and it seems to work fine under the latest versions of both Chrome and Firefox. If there are problems with using Jax on other OS's, there's little I can do until Monday. That's why I'm relying on your help. :)

Keep in mind that you can always revert to an earlier commit. If installed, you can use the "gitk" command for a GUI to help you go back in time. In fact, if you can find the exact commit that broke Linux support, it will be much easier for me to debug!

**Comment by brownman** [comment]
hi Collin, 

currently im working on developing my first rails project, 
and i make use of Three.js (easy to use for one that encounter PaperVision3D before), which has a key feature : switching between rendering with/without webgl.

although i appreciate your skills + effort of developing 3D frameworks,  
- i couldn't find way of using "Divinity" project : and i found it disappointing - because it can be a framework which re-use rails component - such as ActiveRecord. and brings rails to the desktop-development(also good for sharing components between web and non-web applications).
- i couldn't grasp an easy way to use your rails-webgl project: -i think u had to divide your project to smaller packages, maybe as gems, to make the rails's view featured with more webgl-components/rails' helpers.
- regarding jax - i found Three.js very easy , and if I would be able to make good bridges between ruby-javascript i will step one way backward from exploring jax.

--0-0-0-0-0--
i think u should ask your self more frequently: 
- apart from showing great programming skills - do i make the life of other programmers easier ?

hope u get all that with good spirit - keep rocking !
chears :*)

**Comment by brownman** [comment]
how is it possible to start rails console , 
and call ruby-opengl / ffi-opengl 
to draw stuff ?

**Comment by sinisterchipmunk** [comment]
As previously noted:

Divinity was a failed project. One day, perhaps it can be resurrected under Ruby 1.9, but for now I find Jax much more interesting. I believe (perhaps incorrectly, but even so!) that desktop computing is a dying breed, gaming included. I believe they will be superceded by the Internet and cloud-based computing.

As shown in the README, the rails-webgl project has _officially_ been replaced by Jax. I see no reason to continue development on two nearly-identical projects. It makes much more sense to bring Jax to release, and then develop a Rails adapter to streamline Rails-based development.

As for using Rails consoles to initiate OpenGL... It should certainly be possible, but it's an avenue I have never explored and one that I have little interest in (for the same reasons mentioned above). So I don't think I can help you there.

And now for the crux of the issue: as I've stated in the past and outlined in the README, Jax is a work in progress. It's not even released yet. You're dealing with code that's passing _only_ the unit tests, and has seen NO edge cases. When I bring it to release (ideally within a month, but totally subject to my other real-world obligations), I'll start making guarantees about its stability (or, at least, the stability of the officially-released version). Until then, however, it's entirely likely that it could be working fine one day and be completely broken the next. Such is life on the bleeding edge! :)

Anyway, to bring this conversation back on-topic, I'll take a look at the Jax Linux issues when I'm back in Atlanta. My hands are tied until Monday, though if you can find the offending commit before then I'll gladly throw up some experimental code to try and address it.

**Comment by sinisterchipmunk** [comment]
Specs and demos are all running for me on Ubuntu 11.04 using the latest commits. I'll assume one of the previous commits fixed the issue (I've been doing a lot of work on the shaders these past few days). Please reopen if you continue encountering this issue.
