### ISSUE TITLE
Uninitialized constant Jasmine::Config

### ISSUE THREAD

**Issue by MichaelHoste** [sinisterchipmunk/jax#72]
I finally migrated to 3.0.0.rc2 and I had this error when loading a page :

```
NameError (uninitialized constant Jasmine::Config):
  jax (3.0.0.rc2) lib/jax/jasmine/config.rb:1:in `<top (required)>'
  jax (3.0.0.rc2) lib/jax/jasmine/rails_adapter.rb:18:in `middleware'
  jax (3.0.0.rc2) lib/jax/jasmine/rails_adapter.rb:12:in `call'
```

It seems related to https://github.com/searls/jasmine-rails/issues/19

Forcing 'jasmine' 1.3.0 in my Gemfile works but maybe something must be done in the Jax dependencies to avoid this specific issue.

**Comment by sinisterchipmunk** [comment]
Thanks for the bug report. Happily, I was able to pull in `jasmine-rails` and let it take over the asset compilation (this wasn't possible in the past) so Jax is now less tightly coupled to Jasmine. Now I want to run some additional tests before pushing a new release.
