### ISSUE TITLE
Add Jax.Mesh.Icosahedron to builtin meshes

### ISSUE THREAD

**Issue by Goutte** [sinisterchipmunk/jax#75]
I know this would mean opening the door to quite a number of polyhedrons (if only the regular ones), so it's okay if this is not in the right place.

I've been fiddling a bit with the code in order to make it happen, see the [tests stubs](https://github.com/Goutte/jax/blob/icosahedron/spec/javascripts/jax/builtin/meshes/icosahedron_spec.js.coffee) and the [good-enough-until-tests-are-set-up implementation](https://github.com/Goutte/jax/blob/icosahedron/lib/assets/javascripts/jax/builtin/meshes/icosahedron.js.coffee).

I figure an icosahedron is merely a geodesic sphere with complexity 0, so I plan a Jax.Mesh.GeodesicSphere in the long term.

Would you agree these belong in the builtin ? How can I test what I want to test ? Are there jobs for the Model that I fail to see ?

**Comment by sinisterchipmunk** [comment]
First of all, thanks a lot for this! I actually had stored away some icosahedron-generating code from another project (written in Java) just so I could implement this at some unknown point in the future!

`# Is there a (high-level) way of getting the faces ? Is it the model's job ?`

See next answer: it comes down to performance, and enforcing good coding practices.

`# can i haz vertices as Vector3's ? If not, why not ? Perf ? Maybe it's the model's job too ?`

Exactly: performance. In earlier versions of Jax, I stubbornly insisted on providing a way to construct `vec3`'s out of the vertices. In the RC's I have relented, realizing that this unfortunately makes it easy to write Bad Code (TM). In some cases (depending on the model), the delay can be so horrible that it actually stalls the JavaScript process!

Unfortunately, from a testing perspective (or any other situation where you absolutely need higher-level functionality), this means you have to build up your list of faces on your own, which is somewhat non-trivial.

## However....

The backing out of high-level APIs is, I hope, temporary. Not only have the JavaScript engines improved substantially; Web Workers are now a reality in the target browsers. I'm hoping sometime circa Jax 3.1, the entire init process can be off-loaded into Workers, where engine stalls are a non-issue. If there's no danger of alerting the user with an intrusive "Want to kill JavaScript?" prompt, I'm much more amenable to letting developers decide whether an expensive high-level operation is necessary for their particular use cases.

**Comment by Goutte** [comment]
Thanks for the explanations !

I'm all for good practices, but my js-fu is not advanced enough to envision all the problems you mention. I'll be picking your brains along the road quite a bit, I trust ! ^^

I wrote the [icosahedron specs](https://github.com/Goutte/jax/blob/icosahedron/spec/javascripts/jax/builtin/meshes/icosahedron_spec.js.coffee), but it feels like cheating.

Thoughts on how to refactor these so that I may use them in other specs ?

**Comment by Goutte** [comment]
BTW, github's syntax highlighter is going bananas over the #+ horizontal ruler.
I'll remove them during refactoring.

And another question along the way : should I use the vertexWrapper or directly the vertexBuffer ? I suspect the wrapper being an attempt at providing some high-level API, am I right ?

**Comment by Goutte** [comment]
Also wrote the [geodesic sphere specs](https://github.com/Goutte/jax/blob/icosahedron/spec/javascripts/jax/builtin/meshes/geodesic_sphere_spec.js.coffee) and a working [geode](https://github.com/Goutte/jax/blob/icosahedron/lib/assets/javascripts/jax/builtin/meshes/geodesic_sphere.js.coffee).
The geode specs use the same face / vertice high-level accessors as the icosahedron specs, which still are not in the right place / written in the right way. (would that be using @define so we can hook the mutator ? or in `extras` ?)

I'm thinking about the number of subdivisions factor -- what name should it have ?
Complexity ? Detail ? Level ? Depth ? Divisions ? Subdivisions ? NumberOfSubdivisions ?

There is also a [quick demo of the geodes](https://github.com/Goutte/jax/blob/icosahedron/app/assets/jax/controllers/geode.js.coffee).
They initialize way faster than with three.js.

Note that for complexity > 5, the geode is only partially rendered, and looks buggy but pretty ! Probably something to do with the max (65535) number of vertices reached (6 subdivisions => 245760 vertices), I did not try `geode.submesh.recalculateNormals()` yet.

**Comment by Goutte** [comment]
I kind of killed the speed of the demo by brute-adding two rows of textured meshes.
Perf is not the issue here, as I'm trying to pinpoint a _really_ weird bug **randomly** (i insist, that's what baffles me) inverting V-wise the first texture mapping (if the position of the model is Y < 0 -- NO).

Need some shuteye, 'cause this is just _WAT_.

**Comment by sinisterchipmunk** [comment]
This looks great! Can't wait 'til you get the bugs worked out, so we can merge it into Jax master.

> should I use the vertexWrapper or directly the vertexBuffer ?

For now, use the `vertexBuffer`. I would prefer you to use `Jax.Mesh#vertices`, which should ultimately return `vertexBuffer`, but I'm not sure that's working properly as of this writing. Maybe try it out and if it doesn't work, use `mesh.data.vertexBuffer` instead. But in a future version (hopefully before v3.0 is officially born), we'll want to go back to using `Jax.Mesh#vertices`.

>  I suspect the wrapper being an attempt at providing some high-level API, am I right ?

I wish I could say that. It's kind of a long story, but basically, the wrapper is an instance of `FloatBuffer`, a private, internal class defined at the top of `Jax.Mesh.Data`. `FloatBuffer` is a compatibility layer designed to provide the same basic API as an instance of `Jax.Buffer`. It's not meant for public consumption: it is used in the lowest levels of the render process, partially because I haven't deprecated `Jax.Buffer` yet, and partially because I haven't found a better way to do what it does yet. Both of these are temporary problems, and I hope to make the wrappers a thing of the past by the time v3.1 rolls around.

> The geode specs use the same face / vertice high-level accessors as the icosahedron specs

I'd probably put them into a helper, because helpers are guaranteed to all load before the specs but after the sources.

> I'm thinking about the number of subdivisions factor -- what name should it have ?

If there's any kind of accepted standard, then use that. If not, then since you referred to it as "subdivisions factor" in natural speech, I'd say just call it `subdivisions` -- but I'm not too attached to this. You decide. :)

>  Probably something to do with the max (65535) number of vertices reached

`Jax.Mesh` will automatically split large meshes into multiple smaller meshes and render them when the parent mesh is rendered. This is how `submesh` gets populated.

From your source code:

```
# Tangents & Bitangents : should we pre-compute them ?
```

In general, I try not to do this. The tangents and bitangents arrays are provided to `Jax.Mesh` so that they can be populated from a model loader, assuming they have already been baked and the data is handy. If they are to be calculated at runtime, I prefer to let the mesh do that automatically when the tangents and bitangents are actually used. This way, if they're not used, we never have to waste the horsepower trying to calculate them.

**Comment by Goutte** [comment]
Thanks for the pointers. Glad you like it !

I haven't sorted the random Y-flip texture bug ; now I'm not sure if it is an icosahedron bug or a jax bug. My brain fried, so I procrastinated a bit and tackled another mesh : GeodesicSphereDual.

You can see it on the first row :

![geodes_honey](https://f.cloud.github.com/assets/592545/206893/86f8e750-81dd-11e2-9ea7-0bea40d0c42b.png)

Of course, the first mesh is a dodecahedron, but this should **not** be the preferred way of drawing one, because computing the dual of a geodesic sphere is achingly slow (at least, my initial implementation of it is)

I think, given its poor performances, that it does not deserve a place in the builtin ; where should it go ? I'm a bit frightened by plugins, maybe in a `extra` section ?

**Comment by Goutte** [comment]
Added a new `run_webgl_demo` controller to view a demo _fullscreen_, using the fragment identifier of the url.
Eg: http://localhost:3000/run_webgl_demo#geodes
It's using the [jsuri](http://code.google.com/p/jsuri/) lib. (tested, they say)
Haven't found how to setup a different parent template for it, though.

Added a new demo `d20` to better test icosahedron texture mappings, with a simple but neat trackball control. (no pan, no zoom, only rotations). Struggling with the magic of `@define`s.

Fixed (Hid, more accurately) the UV Y-flip bug in the demos by adding the geode to the world **after** the loading of the biggest texture. (ie: in the onload callback).

![D20](https://f.cloud.github.com/assets/592545/228646/106f77ea-8686-11e2-83a6-e7977a7c874e.png)

## Functionality freeze, let's review.
1. The branch is missing tests related to the new controller
2. Some algos could be optimized (in their approach and by clever js scoping), but I don't know how -- using less math is not easy.
3. I heard about the impact on memory of using non-bijective UV mapping -- some pixels of the texture are loaded but never used. Is it a problem, really ? I like editing an isometric texture. BTW, I made a neat GIMP template with handy guides, paths, and text layers for the icosahedron/geode mapping. Is this code ?
4. It uses Math.TAU. I agree Math.TAU belongs mainstream, but then again so do the matrixes, vectors, and quats.
5. Tests, tests, tests ! What's missing ?

**Comment by Goutte** [comment]
Also, i read the section on [helpers](http://guides.jaxgl.com/getting_started.html#helpers), but it's for controllers, not for specs ! Shall I use the `# require` syntax ?

**Comment by Goutte** [comment]
Gave it some more thought. The added demo controller is awful, i'll remove it. Yet being able to view a demo fullscreen would be nice.

**Comment by sinisterchipmunk** [comment]
> Also, i read the section on helpers, but it's for controllers, not for specs !

You're right, there's an ambiguity here that I've never noticed. Jax 'helpers' are essentially mix-ins to help modularize sets of functionality. Jasmine 'helpers' live in `spec/javascripts/helpers` and their purpose is to provide helper functions geared towards unit testing, and extra matchers to make the unit tests more expressive.

I've been wondering whether to deprecate Jax helpers altogether for a long time, and just telling people to use `@include` (or `Function.include`, in pure JS), which is currently an undocumented pattern. I'm still undecided, and will probably not decide prior to releasing v3.0.
