### ISSUE TITLE
avoid redundant operations in Jax.Camera#unproject

### ISSUE THREAD

**Issue by sinisterchipmunk** [sinisterchipmunk/jax#83]
When `winz` is omitted, a ray including values for `winz === 0` and `winz === 1` is returned.

It's unnecessary to build a view/projection matrix once for each `winz`. Stop doing that. The same matrix can be used to unproject both values.

**Comment by Goutte** [comment]
Also, I need to pass `@context.canvas.height - e.y` as second parameter in the mouse callbacks.

**Comment by sinisterchipmunk** [comment]
Thanks - I wasn't aware of that.

**Comment by to-masz** [comment]
Does it work properly at all ?

```
  # calculation for inverting a matrix, computing projection x modelview
  # then compute the inverse
  m = mat4.invert mat4.create(), mm # WHY do I have to invert first?
  mat4.multiply m, pm, m
  return null unless mat4.invert m, m
```

I like the comment "WHY do I have to invert first?". In the oryginal code there is no such operation http://www.opengl.org/wiki/GluProject_and_gluUnProject_code

If you modify transformation matrix of the camera, then mm != mm ^ -1 and it will give strange results
Only for identity matrix m == m^-1

I think, you can replace two lines with:

```
  m = mat4.create()
  mat4.multiply m, pm, mm
```

Check also http://myweb.lmu.edu/dondi/share/cg/unproject-explained.pdf

**Comment by sinisterchipmunk** [comment]
@to-masz The reason for the inversion, I've since learned, is because the camera treats its matrix as a model matrix, not a view matrix. The model matrix converts local (object) space coordinates into world space; the view matrix has the opposite effect, transforming world space into local (eye) space. The latter is accomplished by taking an inverse of the former, when the former represents the orientation of a viewport into the world instead of an object or model within the world.

So unprojection as written in Jax does work properly. It has the extra inversion because its matrix is a model matrix, not a view matrix. The design is a waste of cycles and its performance can be improved upon, but the implementation is logically correct.

I'd remove the "WHY" comment, but I'm in the process of rewriting the camera entirely due to [other issues](https://github.com/sinisterchipmunk/jax/issues/90); I'll just tackle the confusion around unprojection at the same time.
