### ISSUE TITLE
Comments and shader mangling

### ISSUE THREAD

**Issue by Goutte** [sinisterchipmunk/jax#94]
Say you have a material with a MyCustom shader and then the Texture shader in the Layer pipeline.

Say you have, in the `common.glsl` of your MyCustom shader, the following comment somewhere :

```
//shared varying vec2 vTexCoords;
```

All hell will break loose, as shader mangling will not ignore comments.

It's not a critical bug, but it's good to know.

I'd expose this in a test, but I'm in a rush (6 days left before LEAP motion release !)

**Comment by sinisterchipmunk** [comment]
Nice catch, I'll make this a priority. Comments should be ignored in all cases, obviously.

**Comment by sinisterchipmunk** [comment]
> 6 days left before LEAP motion release !

First time I've heard of it! (I guess I've been living under a rock.)

Google: o.O
Youtube: O.O

Preordered.

**Comment by Goutte** [comment]
Heh, I've been waiting for this since may 2012, and pestering my friends and family with it since ; I guess I assume that everybody knows about it... I was denied a dev kit (never again am I gonna write an application being drunk out of my eyes).

I trust it'll integrate seamlessly with other JAX inputs !
